import Head from "next/head";
import Header from "../../components/Header";
import Slider from "../../components/Slider";
import { useState } from "react";
import { BsCart3 } from "react-icons/bs";
import { ImCross, ImPlus, ImMinus } from "react-icons/im";



const product = {
  name: 'Fall Limited Edition Sneakers',
  brand: 'Sneaker Company',
  description: `These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they'll withstand everything the weather can offer.`,
  price: 250.00,
  discount: true,
  discount_percent: .50,
  inventory: 10,
  images: [
    'image-product-1',
    'image-product-2',
    'image-product-3',
    'image-product-4'
  ]
}

export default function Home() {
  const [productAmount, setProductAmount] = useState(0);
  const [currentImage, setCurrentImage] = useState(0);
  const [showSlider, setShowSlider] =useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <div className="container">
          <Header />
          <section className="hero is-fullheight">
            <div className="hero-body">
              <div className="product columns is-align-items-center">
                <div className="column">
                  <div className="images-container">
                    <div className="columns is-flex-wrap-wrap">
                      <div className="column is-12">
                        <img className="main-image" src={`/assets/${product.images[currentImage]}.jpg`} alt="Product Image" />
                      </div>
                      {product?.images.map((item, index) => (
                        <div key={index} className="column is-3 thumbnail">
                          <img onClick={() => (setCurrentImage(index), setShowSlider(true)) } className="thumbnail-image" src={`/assets/${item}.jpg`} alt="" />
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                <div className="column">
                  <div className="product-info">
                    <h6>{product.brand}</h6>
                    <h1>{product.name}</h1>
                    <p>{product.description}</p>
                    <div className="product-price">
                      {product.discount ?
                        <>
                          <h3>${product.price * product.discount_percent}.00 <span>{product.discount_percent * 100}%</span></h3>
                          <h6 className="price">${product.price}</h6>
                        </>
                        :
                        <h3>${product.price}</h3>
                      }
                    </div>
                    <div className="product_checkout">
                      <div className="product_amount">
                        <span className="icon" onClick={() => setProductAmount(productAmount - 1)} ><ImMinus /></span>
                        <span>{productAmount}</span>
                        <span className="icon" onClick={() => setProductAmount(productAmount + 1)}><ImPlus /></span>
                      </div>
                      <button className="button is-primary">
                        <span className="icon is-large m-0"><BsCart3 /></span> Add to cart
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
        <Slider data={product.images} currentSlide={currentImage} state={showSlider}>
          <span className="icon is-large m-0" onClick={() => setShowSlider(false)}><ImCross /></span>
        </Slider>
      </main>
    </>
  );
}