import Head from "next/head";
import Header from "../../components/Header";
import { BsCart3 } from "react-icons/bs";
import { ImPlus, ImMinus } from "react-icons/im";
import { useState } from "react";



const product = {
  name: 'Fall Limited Edition Sneakers',
  brand: 'Sneaker Company',
  description: `These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they'll withstand everything the weather can offer.`,
  price: 250.00,
  discount: true,
  discount_percent: .50,
  inventory: 10,
  images: [
    '/assets/image-product-1.jpg',
    '/assets/image-product-2.jpg',
    '/assets/image-product-3.jpg',
    '/assets/image-product-4.jpg'
  ]
}

export default function Home() {
  const [productAmount, setProductAmount] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <div className="container">
          <Header />
          <section className="hero is-fullheight">
            <div className="hero-body">
              <div className="product columns is-align-items-center">
                <div className="column">
                  <img src="/assets/image-product-1.jpg" />
                </div>
                <div className="column">
                  <div className="product-info">
                    <h6>{product.brand}</h6>
                    <h1>{product.name}</h1>
                    <p>{product.description}</p>
                    <div className="product-price">
                      {product.discount ?
                        <>
                          <h3>${product.price * product.discount_percent}.00 <span>{product.discount_percent * 100}%</span></h3>
                          <h6 className="price">${product.price}</h6>
                        </>
                        :
                        <h3>${product.price}</h3>
                      }
                    </div>
                    <div className="product_checkout">
                      <div className="product_amount">
                        <span className="icon" onClick={() => setProductAmount(productAmount-1)} ><ImMinus /></span>
                        <span>{productAmount}</span>
                        <span className="icon" onClick={() => setProductAmount(productAmount+1)}><ImPlus /></span>
                      </div>
                      <button className="button is-primary">
                        <span className="icon is-large m-0"><BsCart3 /></span> Add to cart
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}